name: Lint and Build

on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get App's cache
        uses: actions/cache@v2
        id: app_cache
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-app1-${{ hashFiles('package-lock.json', '.github/workflows/lint_build.yml') }}

      - name: Show cache status
        run: |
          echo ${{steps.app_cache.outputs.cache-hit}}
      - name: Get Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Use npm version 7
        run: |
          npm install -g npm@7
      - name: Install dependencies
        run: npm ci
        if: steps.app_cache.outputs.cache-hit != 'true'

      - name: Install rc-apps CLI
        # install rc-apps in node_modules so that it can be cached
        run: |
          npm install @rocket.chat/apps-cli --no-save
          ./node_modules/.bin/rc-apps -v
      - name: Cache all of the above for next steps
        uses: actions/cache@v2
        id: cache_app_actions
        with:
          path: |
            ./*
          key: app_actions-${{github.sha}}

  lint:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Restore cache
        uses: actions/cache@v2
        id: restore_app_actions_cache
        with:
          path: ./*
          key: app_actions-${{github.sha}}

      - name: Check lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Restore cache
        uses: actions/cache@v2
        id: restore_app_actions_cache
        with:
          path: |
            ./*
          key: app_actions-${{github.sha}}
      - name: show bin
        run: |
          ls ./node_modules/.bin
      - name: Package as Rocket.Chat app
        run: ./node_modules/.bin/rc-apps package